config/routes.rb
Rails.application.routes.draw do

  # Air One

  root to: 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips', to: 'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  get 'search', to: 'pages#search'

  # Air Two

  get 'dashboard', to: 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end

  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"

  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'

  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

end

app/views/shared/_devise_flashes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fa fa-heart"></i> by Nick
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon" style="margin-bottom: 0px;">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <a href="/" class="navbar-brand">
      AirTwo
    </a>

    <% if current_page?(search_path) %>
      <div id="navbar" class="navbar-collapse collapse">
        <%= form_tag  search_path, class: "navbar-form navbar-left", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Essayez \"Paris\"", class: "form-control", id: "navbar-geo" %>
          </div>
          <%= button_tag(type: "submit") do %>
              <i class="fa fa-search"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <%= link_to  "Listings", rooms_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to  "Reservations", your_reservations_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to  "Trips", your_trips_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <i class="fa fa-bell fa-2x icon-babu"></i>
        <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
      <% end %>

      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <a href="#" class="dropdown-toggle navbar-wagon-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="navbar-wagon-menu">
            <% if gravatar?(current_user) %>
              <%= image_tag avatar_url(current_user), class: "avatar" %>&nbsp;
            <% else %>
              <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar">&nbsp;
            <% end %>
            <span class="navbar-wagon-link"><%= current_user.fullname %></span>
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to  "Dashboard", dashboard_path %></li>
            <li><%= link_to  "Manage Listings", rooms_path %></li>
            <li><%= link_to "List Your Space", new_room_path %></li>
            <li><%= link_to "Your Reservations", your_reservations_path %></li>
            <li><%= link_to  "Your Trips", your_trips_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Manage Listings</a></li>
        <li><a href="#">List Your Space</a></li>
        <li><a href="#">Your Reservations</a></li>
        <li><a href="#">Your Trips</a></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</div>

<% if (user_signed_in?) && !current_page?(root_path) && (current_user.rooms.size != nil) && !current_page?(search_path) && !((controller_name.eql? "rooms") && (action_name.eql? "show")) %>
  <nav class="navbar navbar-default" style="background-color: #3B4355; margin-bottom: 0; border: 0;">
    <div class="container">
      <ul class="nav navbar-nav">
        <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
        <li <% if current_page?(rooms_path) %> class="active" <% end %> ><%= link_to "Manage Listings", rooms_path %></li>
        <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
        <li <% if current_page?(revenues_path) %> class="active" <% end %> ><%= link_to "Revenues", revenues_path %></li>
        <li <% if current_page?(host_calendar_path) %> class="active" <% end %> ><%= link_to "Calendar", host_calendar_path %></li>
        <li <% if current_page?(payment_method_path) %> class="active" <% end %> ><%= link_to "Account Settings", payment_method_path %></li>
      </ul>
    </div>
  </nav>
<% end %>

<script>
  $(function() {
    $("#navbar-geo").geocomplete();
  });
</script>